name: dune build
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    name: dune build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup dune
        uses: nmittu/setup-dune@v2
        with:
          packages: "js_of_ocaml ppx_jane js_of_ocaml-ppx incr_dom ojs ocamlformat.0.21.0"
          compiler: 4.12.0
      - name: Build
        run: |
          eval $(opam config env)
          dune build bin/{index.html,main.bc.js,shuffle.png,loop.png}