on:
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install dune
        run: |
          sudo apt-get update
          sudo apt-get install opam
          opam init
      - name: Install opam packages
        run: |
          opam install dune js_of_ocaml ppx_jane js_of_ocaml-ppx incr_dom ojs
      - name: build
        run: |
          dune build bin/{index.html,main.bc.js}
          
      
